import "./table-title/block.js";
import "./table-thick/block.js";
import "./table-kg/block.js";
import "./table-physical-property/block.js";
import "./table-details/block.js";
import "./case/block.js";
import "./case-and-item/block.js";
import "./remarks/block.js";
import "./slider/block.js";
